services:
  blog-db:
    image: mysql
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - blog-db-vol:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - blog-net
    secrets:
      - db_password
  blog-server:
    image: mibitstech/blog-app:build-8a422e17f3f72cdd24811ba4c8e6d95ac8f10138
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - http://localhost:3000/health
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '3001:3000'
    environment:
      - DB_HOST=blog-db
      - DB_USER_FILE=/run/secrets/db_username
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_NAME=blogdb
      - NODE_HOST="{{.Node.Hostname}}"
    networks:
      - blog-net
volumes:
  blog-db-vol: null
networks:
  blog-net: null
secrets:
  db_password:
    external: true
  db_username:
    external: true
